### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: -4

### ISSUE THREAD

**Issue by svaccari** [StevenLooman/magik-tools#20]
Hi,

Using versione 5.3 I receive this error on random files in my repo (> 2K Magik files).
I'm trying to create a minimal reproducible test, meanwhile I'm opening this issue, thanks. 

<pre>
17:24:36.084 DEBUG: Saving metric, file: error.magik, metric: Metric[uuid=<null>,key=complexity,description=Cyclomatic complexity,type=INT,direction=-1,domain=Complexity,name=Cyclomatic Complexity,qualitative=false,userManaged=false,enabled=true,worstValue=<null>,bestValue=<null>,optimizedBestValue=false,hidden=false,deleteHistoricalData=false,decimalScale=<null>] value: 1
17:24:36.084 DEBUG: Running checks
17:24:36.084 DEBUG: Running check: nl.ramsolutions.sw.magik.checks.checks.UnusedVariableCheck@1d458c1e
17:24:36.085 DEBUG: Running check: nl.ramsolutions.sw.magik.checks.checks.SimplifyIfCheck@5d3b2d9a
17:24:36.085 DEBUG: Running check: nl.ramsolutions.sw.magik.checks.checks.SizeZeroEmptyCheck@1534fd96
17:24:36.085 DEBUG: Running check: nl.ramsolutions.sw.magik.checks.checks.LhsRhsComparatorEqualCheck@6283ac9
17:24:36.085 DEBUG: Running check: nl.ramsolutions.sw.magik.checks.checks.ForbiddenCallCheck@60607fab
17:24:36.085 DEBUG: Running check: nl.ramsolutions.sw.magik.checks.checks.SyntaxErrorCheck@5011753d
17:24:36.085 DEBUG: Running check: nl.ramsolutions.sw.magik.checks.checks.VariableNamingCheck@2fb90f1
17:24:36.085 DEBUG: Running check: nl.ramsolutions.sw.magik.checks.checks.LocalImportProcedureCheck@5d4b0fac
17:24:36.085 DEBUG: Running check: nl.ramsolutions.sw.magik.checks.checks.MethodDocCheck@2b84d474
17:24:36.092 INFO: 105/239 files analyzed, current file: error.magik
17:24:36.095 INFO: ------------------------------------------------------------------------
17:24:36.095 INFO: EXECUTION FAILURE
17:24:36.095 INFO: ------------------------------------------------------------------------
17:24:36.095 INFO: Total time: 17.557s
17:24:36.147 INFO: Final Memory: 17M/74M
17:24:36.147 INFO: ------------------------------------------------------------------------
17:24:36.147 ERROR: Error during SonarScanner execution
java.lang.StringIndexOutOfBoundsException: String index out of range: -4
	at java.base/java.lang.String.substring(Unknown Source)
	at nl.ramsolutions.sw.magik.parser.MethodDocParser.lambda$extractSectionText$3(MethodDocParser.java:180)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at nl.ramsolutions.sw.magik.parser.MethodDocParser.extractSectionText(MethodDocParser.java:182)
	at nl.ramsolutions.sw.magik.parser.MethodDocParser.lambda$getParameterTexts$2(MethodDocParser.java:163)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Unknown Source)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at nl.ramsolutions.sw.magik.parser.MethodDocParser.getParameterTexts(MethodDocParser.java:159)
	at nl.ramsolutions.sw.magik.checks.checks.MethodDocCheck.walkPreMethodDefinition(MethodDocCheck.java:42)
	at nl.ramsolutions.sw.magik.analysis.AstWalker.walkAst(AstWalker.java:81)
	at nl.ramsolutions.sw.magik.analysis.AstWalker.walkChildren(AstWalker.java:21)
	at nl.ramsolutions.sw.magik.analysis.AstWalker.walkAst(AstWalker.java:70)
	at nl.ramsolutions.sw.magik.MagikVisitor.scanFile(MagikVisitor.java:25)
	at nl.ramsolutions.sw.magik.checks.MagikCheck.scanFileForIssues(MagikCheck.java:70)
	at nl.ramsolutions.sw.sonar.sensors.MagikSquidSensor.scanMagikFile(MagikSquidSensor.java:128)
	at nl.ramsolutions.sw.sonar.sensors.MagikSquidSensor.execute(MagikSquidSensor.java:97)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:399)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:395)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:364)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:135)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
</pre>

**Comment by StevenLooman** [comment]
Thank you for this issue @svaccari. Is this the only error you're getting, or are there other errors as well? Hopefully I can fix all those errors and release a single version, instead of going version through version.

I plan on removing the method doc check, as it is very specific to one/a few companies. But still, perhaps you can pinpoint the method (and its comments) causing the error and provide a use case I can test with?

**Comment by svaccari** [comment]
Hi,

this is the only blocking error I get any time I try to parse a specific file.
I'm attaching a minimal example to reproduce the bug, hope it helps.

[test.magik.txt](https://github.com/StevenLooman/magik-tools/files/9950114/test.magik.txt)

(I had to rename .txt due to github policies...)

**Comment by svaccari** [comment]
[test_complete.magik.txt](https://github.com/StevenLooman/magik-tools/files/9956131/test_complete.magik.txt)

This is the complete file.
It seems like a customization of an original Smallworld source file - comments are surely not originated within my company - but I will try asking for further information

**Comment by svaccari** [comment]
Entire repo (> 2K files) analysed successfully, thanks!
